# Ames Housing — Pipeline, ColumnTransformer, and Ridge vs. LinearRegression

Applying Pipeline, SimpleImputer, and ColumnTransformer to Kaggle's Ames Housing dataset
(1460 houses, 81 columns), then comparing Ridge Regression against a plain LinearRegression
baseline under 5-fold cross-validated RMSE.

Requires `ames_train.csv` in `../data/` relative to this notebook.

In [1]:
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

### Loading Data

In [2]:
df = pd.read_csv('../data/ames_train.csv')
print(f"Shape: {df.shape}")
df.head(3)

Shape: (1460, 81)


,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500


### The Nan-doesn't-mean-missing trap

Several columns use NaN to mean "this feature doesn't exist for this house" (no pool, no
alley, no fence, no fireplace, no garage), not "value unknown." Confirming this before
deciding what to impute avoids inventing values for houses that simply lack a given feature.

In [3]:
df.isna().sum().sort_values(ascending=False).head(20)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
Electrical         1
Id                 0
dtype: int64

In [4]:
na_means_absent = ['PoolQC', 'Alley', 'Fence', 'FireplaceQu', 'GarageType']
for col in na_means_absent:
    print(f"{col}: {df[col].isna().sum()} NaN out of {len(df)}  (NaN = feature absent, not unknown)")

print()
genuinely_missing = ['LotFrontage', 'Electrical']
for col in genuinely_missing:
    print(f"{col}: {df[col].isna().sum()} NaN out of {len(df)}  (NaN = genuinely unrecorded)")

PoolQC: 1453 NaN out of 1460  (NaN = feature absent, not unknown)
Alley: 1369 NaN out of 1460  (NaN = feature absent, not unknown)
Fence: 1179 NaN out of 1460  (NaN = feature absent, not unknown)
FireplaceQu: 690 NaN out of 1460  (NaN = feature absent, not unknown)
GarageType: 81 NaN out of 1460  (NaN = feature absent, not unknown)

LotFrontage: 259 NaN out of 1460  (NaN = genuinely unrecorded)
Electrical: 1 NaN out of 1460  (NaN = genuinely unrecorded)


### Selecting a Feature Subset

81 columns is too many to hand-reason about, picking a mix of intuitive predictors (size,
quality, location) rather than throwing every column in.

In [5]:
numeric_features = [
    'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt',
    'TotalBsmtSF', 'GrLivArea', 'FullBath', 'BedroomAbvGr',
    'GarageCars', 'GarageArea'
]

categorical_features = [
    'MSZoning', 'Neighborhood', 'HouseStyle', 'ExterQual',
    'KitchenQual', 'SaleCondition'
]

target = 'SalePrice'

X = df[numeric_features + categorical_features]
y = df[target]

In [6]:
print(f"Missing values in selected numeric columns:\n{X[numeric_features].isna().sum()[X[numeric_features].isna().sum() > 0]}")
print(f"\nMissing values in selected categorical columns:\n{X[categorical_features].isna().sum()[X[categorical_features].isna().sum() > 0]}")

Missing values in selected numeric columns:
Series([], dtype: int64)

Missing values in selected categorical columns:
Series([], dtype: int64)


### Train/Test Split

Splitting before any preprocessing is fit, so the imputer, scaler, and encoder in the
upcoming ColumnTransformer only ever see training data until prediction time.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Train: {X_train.shape} | Test: {X_test.shape}")

Train: (1168, 16) | Test: (292, 16)


### Building the ColumnTransformer

Each branch (numeric, categorical) is itself a small Pipeline: impute, then scale/encode.
Both branches run in parallel and get concatenated back into one array.

In [8]:
numeric_transformer = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

categorical_transformer = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encode', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [9]:
preprocessor.fit(X_train)
X_train_transformed = preprocessor.transform(X_train)
print(f"Original feature count: {len(numeric_features + categorical_features)}")
print(f"Transformed shape: {X_train_transformed.shape}")

Original feature count: 16
Transformed shape: (1168, 62)


### Full Pipeline — fit and predict end-to-end

Wiring the preprocessor and a model into one Pipeline. Today's bar: clean fit → predict,
no errors.

In [10]:
full_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', LinearRegression())
])

full_pipe.fit(X_train, y_train)
predictions = full_pipe.predict(X_test)

In [11]:
comparison = pd.DataFrame({
    'predicted': predictions[:5].round(0),
    'actual': y_test.values[:5]
})
comparison

,predicted,actual
0,150875.0,154500
1,320575.0,325000
2,114424.0,115000
3,173498.0,159000
4,297501.0,315500


### Quick sanity metric

Not the real evaluation, that's next with proper cross-validation, just confirming the
predictions are in a sane ballpark relative to actual sale prices.

In [12]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, predictions)
print(f"Mean Absolute Error: ${mae:,.0f}")
print(f"Average sale price in test set: ${y_test.mean():,.0f}")
print(f"MAE as % of average price: {mae / y_test.mean() * 100:.1f}%")

Mean Absolute Error: $19,549
Average sale price in test set: $178,840
MAE as % of average price: 10.9%


### Ridge Regression vs. LinearRegression under cross-validated RMSE

Replacing the single train/test split evaluation from Section 6 with proper 5-fold
cross-validated RMSE. One KFold splitter is reused for both models so the comparison runs
on identical folds. Cross-validation runs on X_train/y_train only, X_test stays untouched.

In [13]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import KFold, cross_val_score

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

linreg_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', LinearRegression())
])

ridge_pipe = Pipeline([
    ('preprocess', preprocessor),
    ('model', Ridge())
])

linreg_scores = -cross_val_score(
    linreg_pipe, X_train, y_train, cv=kfold, scoring='neg_root_mean_squared_error'
)
ridge_scores = -cross_val_score(
    ridge_pipe, X_train, y_train, cv=kfold, scoring='neg_root_mean_squared_error'
)

print(f"Linear Regression CV RMSE: {linreg_scores.mean():,.0f}  (+/- {linreg_scores.std():,.0f})")
print(f"Ridge Regression CV RMSE:  {ridge_scores.mean():,.0f}  (+/- {ridge_scores.std():,.0f})")

Linear Regression CV RMSE: 34,090  (+/- 5,716)
Ridge Regression CV RMSE:  33,909  (+/- 5,868)


In [14]:
df[numeric_features].corr().round(2)

,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,GrLivArea,FullBath,BedroomAbvGr,GarageCars,GarageArea
LotArea,1.00,0.11,-0.01,0.01,0.26,0.26,0.13,0.12,0.15,0.18
OverallQual,0.11,1.00,-0.09,0.57,0.54,0.59,0.55,0.10,0.60,0.56
OverallCond,-0.01,-0.09,1.00,-0.38,-0.17,-0.08,-0.19,0.01,-0.19,-0.15
YearBuilt,0.01,0.57,-0.38,1.00,0.39,0.20,0.47,-0.07,0.54,0.48
TotalBsmtSF,0.26,0.54,-0.17,0.39,1.00,0.45,0.32,0.05,0.43,0.49
GrLivArea,0.26,0.59,-0.08,0.20,0.45,1.00,0.63,0.52,0.47,0.47
FullBath,0.13,0.55,-0.19,0.47,0.32,0.63,1.00,0.36,0.47,0.41
BedroomAbvGr,0.12,0.10,0.01,-0.07,0.05,0.52,0.36,1.00,0.09,0.07
GarageCars,0.15,0.60,-0.19,0.54,0.43,0.47,0.47,0.09,1.00,0.88
GarageArea,0.18,0.56,-0.15,0.48,0.49,0.47,0.41,0.07,0.88,1.00


## 8. Conclusion

Ridge (33,909 ± 5,868) and LinearRegression (34,090 ± 5,716) land within about 180 of each
other on CV RMSE, a fraction of either model's own fold-to-fold standard deviation. Ridge
comes out marginally ahead, but the gap isn't meaningful against that spread.

That's the expected result for this feature set, not a surprising one. Real collinearity is
present among the numeric features: `GarageCars` and `GarageArea` correlate at 0.88, and
`OverallQual` correlates at 0.5-0.6 with `YearBuilt`, `TotalBsmtSF`, `GrLivArea`, and both
garage columns. `OneHotEncoder` also leaves each categorical group's dummies summing to 1,
which is perfect collinearity within that group. Ridge exists to tame exactly this kind of
correlation.

But regularisation only earns its keep when the design matrix is unstable relative to the
data available, and it isn't here. 1,168 training rows against 62 post-encoding columns is a
comfortable n >> p regime: OLS coefficients stay well-estimated even with the collinear pairs
present, so the default `alpha=1.0` shrinkage has little to correct. Ridge would likely show a
bigger edge with a smaller training set, more one-hot-expanded categories (`Neighborhood` alone
already accounts for a large share of the 62 columns), or an `alpha` actually tuned via
`RidgeCV`/`GridSearchCV` rather than left at its default.

One note on comparing to Section 6: the $19,549 MAE there and the ~$34,000 RMSE here aren't
directly comparable. RMSE squares errors before averaging, so it weights large misses (the
houses this feature set predicts worst) more heavily than MAE does. A higher RMSE than MAE on
the same data is expected, not a regression in performance.

## 9. Week 8 Capstone — Feature Engineering

Adding 8 new features to the feature set above: 3 ratio features, 2 interaction features,
2 date-decomposition features (house age, remodel age), and 1 binned feature. Also
log-transforming `SalePrice` and the most skewed numeric inputs.

Two raw columns not in the original feature set are needed to build these — `YearRemodAdd`
and `YrSold` — so the input frame is widened to include them. They're only used to derive
`HouseAge`/`RemodAge`; the raw year values themselves aren't fed to the model directly.

In [15]:
raw_extra_features = ['YearRemodAdd', 'YrSold']

X2 = df[numeric_features + categorical_features + raw_extra_features]

# Same test_size/random_state as the original split, so this produces the identical
# train/test row partition as X_train/X_test above, just with two extra source columns.
X2_train, X2_test, y_train2, y_test2 = train_test_split(X2, y, test_size=0.2, random_state=42)
print(f"Train: {X2_train.shape} | Test: {X2_test.shape}")

Train: (1168, 18) | Test: (292, 18)


### Feature engineering function

All 8 features are built from the **raw** columns (not the log-transformed versions used
later), so ratios and interactions stay in interpretable, real-world units.

Two guards worth calling out, both found by checking the data rather than assuming:
- `BedroomAbvGr` is 0 for 6 houses — dividing by it directly would produce `inf`, so the
  denominator is floored at 1 for that ratio.
- One row has `YearRemodAdd > YrSold` (a known quirk in this dataset), which would give a
  negative remodel age — both age features are clipped at 0.

`LotSizeCategory` uses fixed, domain-chosen bin edges (`0/5000/10000/15000/inf`) rather than
`pd.qcut`, which derives edges from the data's own quantiles. Fixed edges mean the bin
boundaries can't shift between cross-validation folds.

In [16]:
from sklearn.preprocessing import FunctionTransformer

LOT_SIZE_BINS = [0, 5000, 10000, 15000, np.inf]
LOT_SIZE_LABELS = ['Small', 'Medium', 'Large', 'XLarge']


def engineer_features(X: pd.DataFrame) -> pd.DataFrame:
    X = X.copy()

    # Ratio features
    X['LivAreaToLotRatio'] = X['GrLivArea'] / X['LotArea']
    X['BsmtToLivRatio'] = X['TotalBsmtSF'] / X['GrLivArea']
    bedrooms_safe = X['BedroomAbvGr'].replace(0, 1)
    X['BathsPerBedroom'] = X['FullBath'] / bedrooms_safe

    # Date decomposition features
    X['HouseAge'] = (X['YrSold'] - X['YearBuilt']).clip(lower=0)
    X['RemodAge'] = (X['YrSold'] - X['YearRemodAdd']).clip(lower=0)

    # Interaction features (RemodAge/HouseAge must exist first)
    X['QualXArea'] = X['OverallQual'] * X['GrLivArea']
    X['QualXAge'] = X['OverallQual'] * X['HouseAge']

    # Binned feature
    X['LotSizeCategory'] = pd.cut(
        X['LotArea'], bins=LOT_SIZE_BINS, labels=LOT_SIZE_LABELS
    ).astype(str)

    return X


feature_engineer = FunctionTransformer(engineer_features)

engineer_features(X2_train).head(3)

,LotArea,OverallQual,OverallCond,YearBuilt,TotalBsmtSF,GrLivArea,FullBath,BedroomAbvGr,GarageCars,GarageArea,...,YearRemodAdd,YrSold,LivAreaToLotRatio,BsmtToLivRatio,BathsPerBedroom,HouseAge,RemodAge,QualXArea,QualXAge,LotSizeCategory
254,8400,5,6,1957,1314,1314,1,3,1,294,...,1957,2010,0.156429,1.000000,0.333333,53,53,6570,265,Medium
1066,7837,6,7,1993,799,1571,2,3,2,380,...,1994,2009,0.200459,0.508593,0.666667,16,15,9426,96,Medium
638,8777,5,7,1910,796,796,1,2,0,0,...,1950,2008,0.090692,1.000000,0.500000,98,58,3980,490,Medium


### Rebuilding the `ColumnTransformer`

Same two branches as Section 5, plus a third: `GrLivArea`, `LotArea`, and `TotalBsmtSF` are
the most right-skewed numeric inputs in this feature set (skew 1.37 / 12.21 / 1.52 measured
directly on the training data), so they get `log1p` before scaling. `GarageArea` (skew 0.18)
stays in the plain numeric branch — it isn't actually skewed enough to need it.

The 6 new numeric features (ratios, interactions, ages) join the existing numeric branch;
`LotSizeCategory` joins the existing categorical branch.

In [17]:
skewed_numeric_features = ['GrLivArea', 'LotArea', 'TotalBsmtSF']

engineered_numeric_features = [
    'LivAreaToLotRatio', 'BsmtToLivRatio', 'BathsPerBedroom',
    'QualXArea', 'QualXAge', 'HouseAge', 'RemodAge',
]

numeric_features_v2 = [
    f for f in numeric_features if f not in skewed_numeric_features
] + engineered_numeric_features

categorical_features_v2 = categorical_features + ['LotSizeCategory']

numeric_transformer_v2 = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

skewed_numeric_transformer = Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('log1p', FunctionTransformer(np.log1p)),
    ('scale', StandardScaler())
])

categorical_transformer_v2 = Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('encode', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor_v2 = ColumnTransformer([
    ('num', numeric_transformer_v2, numeric_features_v2),
    ('num_skewed', skewed_numeric_transformer, skewed_numeric_features),
    ('cat', categorical_transformer_v2, categorical_features_v2)
])

print(f"New numeric features: {len(numeric_features_v2)}")
print(f"Skewed (log1p) numeric features: {len(skewed_numeric_features)}")
print(f"New categorical features: {len(categorical_features_v2)}")

New numeric features: 14
Skewed (log1p) numeric features: 3
New categorical features: 7


### Log-transforming the target

`SalePrice` has skew 1.88 — skewed enough that a linear model benefits from predicting
`log1p(SalePrice)` instead. Rather than transforming `y` by hand (which would require
manually un-transforming every prediction before scoring), `TransformedTargetRegressor`
wraps each model: it fits on `log1p(y)` internally and automatically applies `expm1` to
predictions before they're returned. That means `cross_val_score`'s RMSE comes back in
**original dollar scale**, directly comparable to the 34,090 / 33,909 baseline from
Section 7 — not in log-dollars.

In [18]:
from sklearn.compose import TransformedTargetRegressor

linreg_pipe_v2 = Pipeline([
    ('feature_engineer', feature_engineer),
    ('preprocess', preprocessor_v2),
    ('model', TransformedTargetRegressor(
        regressor=LinearRegression(), func=np.log1p, inverse_func=np.expm1
    ))
])

ridge_pipe_v2 = Pipeline([
    ('feature_engineer', feature_engineer),
    ('preprocess', preprocessor_v2),
    ('model', TransformedTargetRegressor(
        regressor=Ridge(), func=np.log1p, inverse_func=np.expm1
    ))
])

linreg_scores_v2 = -cross_val_score(
    linreg_pipe_v2, X2_train, y_train2, cv=kfold, scoring='neg_root_mean_squared_error'
)
ridge_scores_v2 = -cross_val_score(
    ridge_pipe_v2, X2_train, y_train2, cv=kfold, scoring='neg_root_mean_squared_error'
)

print(f"Linear Regression CV RMSE (new features): {linreg_scores_v2.mean():,.0f}  (+/- {linreg_scores_v2.std():,.0f})")
print(f"Ridge Regression CV RMSE (new features):  {ridge_scores_v2.mean():,.0f}  (+/- {ridge_scores_v2.std():,.0f})")

Linear Regression CV RMSE (new features): 32,181  (+/- 7,535)
Ridge Regression CV RMSE (new features):  32,160  (+/- 7,879)


### Before / after comparison

In [19]:
comparison_table = pd.DataFrame({
    'Model': ['LinearRegression', 'Ridge'],
    'Baseline CV RMSE': [linreg_scores.mean(), ridge_scores.mean()],
    'New CV RMSE': [linreg_scores_v2.mean(), ridge_scores_v2.mean()],
})
comparison_table['Delta'] = comparison_table['New CV RMSE'] - comparison_table['Baseline CV RMSE']
comparison_table['% Improvement'] = -comparison_table['Delta'] / comparison_table['Baseline CV RMSE'] * 100

comparison_table.round(1)

,Model,Baseline CV RMSE,New CV RMSE,Delta,% Improvement
0,LinearRegression,34090.4,32181.3,-1909.1,5.6
1,Ridge,33909.4,32160.0,-1749.4,5.2


## 10. Submission file (stand-in)

Kaggle's actual `test.csv` for this competition (the unlabeled 1459-row holdout set) isn't
available in this repo or environment. In place of a real leaderboard submission, this
section fits the better-performing model (Ridge, per the comparison above) on `X2_train`
and predicts on the existing held-out `X2_test` split — the same 20% split carved out
earlier, which does have known `SalePrice` values.

**This is a format stand-in, not a real Kaggle submission** — `X2_test` isn't Kaggle's test
set and its `SalePrice` values are already known, so it can't be scored on the leaderboard.
It only demonstrates producing a correctly-shaped `Id, SalePrice` CSV from the final fitted
pipeline.

In [20]:
ridge_pipe_v2.fit(X2_train, y_train2)
submission_predictions = ridge_pipe_v2.predict(X2_test)

submission_ids = df.loc[X2_test.index, 'Id']
submission_df = pd.DataFrame({
    'Id': submission_ids.values,
    'SalePrice': submission_predictions
})

submission_path = '../data/submission_stub.csv'
submission_df.to_csv(submission_path, index=False)

print(f"Wrote {len(submission_df)} rows to {submission_path}")
submission_df.head(3)

Wrote 292 rows to ../data/submission_stub.csv


,Id,SalePrice
0,893,150837.714485
1,1106,306660.317927
2,414,112101.482036
